"""
Django settings for Control_de_Venta project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import os
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$xmrdwnv%2&@#2w15vy@%&!o)#tkucm+!$8)s#@j=6e&i$g=1)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS =  ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # The app is located at Control_de_Venta/tienda and should be
    # imported as the top-level package 'tienda' so Django can find it
    # regardless of whether the project is executed from the repo root
    # or from the nested project folder on the host (Render/Railway/etc.).
    'tienda',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise middleware serves static files efficiently in production
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# The project layout places the actual Django project package at
# Control_de_Venta/Control_de_Venta, so use the full import path for URL
# configuration to avoid ModuleNotFoundError in deployed environments.
ROOT_URLCONF = 'Control_de_Venta.Control_de_Venta.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Point to the inner wsgi module (same package as settings).
WSGI_APPLICATION = 'Control_de_Venta.Control_de_Venta.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration
# Prefer a single DATABASE_URL env var (recommended for Render/Supabase).
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    from urllib.parse import urlparse

    parsed = urlparse(DATABASE_URL)
    # Try to resolve the hostname to an IPv4 address and verify connectivity
    # to avoid IPv6 "Network is unreachable" issues on some hosts (Render).
    host_to_use = parsed.hostname
    try:
        import socket

        def find_working_ipv4(hostname, port, timeout=2):
            try:
                infos = socket.getaddrinfo(hostname, port, family=socket.AF_INET)
            except Exception:
                return None
            for info in infos:
                sockaddr = info[4]
                ip = sockaddr[0]
                try:
                    # Try a short connection to verify reachability
                    with socket.create_connection((ip, port), timeout=timeout):
                        return ip
                except Exception:
                    continue
            return None

        port_to_test = parsed.port or 5432
        ipv4 = find_working_ipv4(parsed.hostname, port_to_test)
        if not ipv4:
            # Try the common Supabase pooler port as a fallback (6543)
            ipv4 = find_working_ipv4(parsed.hostname, 6543)
            if ipv4:
                port_to_test = 6543
        if ipv4:
            host_to_use = ipv4
            parsed_port = port_to_test
        else:
            parsed_port = parsed.port or '5432'
    except Exception:
        # If anything goes wrong, fall back to the DNS hostname and original port
        host_to_use = parsed.hostname
        parsed_port = parsed.port or '5432'

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed.path[1:],
            'USER': parsed.username,
            'PASSWORD': parsed.password,
            'HOST': host_to_use,
            'PORT': parsed_port,
            'OPTIONS': {'sslmode': 'require'},
        }
    }
else:
    # Fallback to individual environment variables (useful for local dev)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'postgres'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }

# Default connection age (0 = close per request). Adjust if you need pooling.
DATABASES['default'].setdefault('CONN_MAX_AGE', 0)



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Use WhiteNoise to serve static files in production (works with collectstatic).
# CompressedManifestStaticFilesStorage embeds file hashes into names for long-
# lived caching. If collectstatic fails due to missing references, consider
# switching to 'whitenoise.storage.CompressedStaticFilesStorage'.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
