# Generated by Django 5.2.6 on 2025-10-27 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_cliente_correo_alter_venta_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe ser 10 dígitos seguidos o 8 dígitos + "-" + dígito verificador (num o K).', regex='^(?:\\d{10}|\\d{8}-[0-9Kk])$')]),
        ),
    ]
